apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: api-mssql-go
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /tickets|/tickets/.*|/ticketcategories/.*|/ticketcategories|/productservicecategories/.*|/servicecataloglvl1/.*|/servicecataloglvl2/.*|/servicecataloglvl3/.*|/servicecataloglvl4/.*|/servicecataloglvl5/.*|/servicecataloglvl6/.*|/productservicecategories|/servicecataloglvl1|/servicecataloglvl2|/servicecataloglvl3|/servicecataloglvl4|/servicecataloglvl5|/servicecataloglvl6
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
  service:
    host: api-mssql-go-servicecat
    name: api-mssql-go
    port: 80
