apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: api-mssql-go-event-sub
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.mp-commerce-mock.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://api-mssql-go.dev.svc.cluster.local:80/orderCodeEvent 